name: Deploy APK to Firebase App Distribution

on:
  release:
    types: [published]
  workflow_dispatch: # برای اجرای دستی با دکمه

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download APK from Latest Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # دانلود خودکار فایل APK موجود در آخرین رلیز شما
          gh release download --pattern "*.apk" --dir .

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute $(ls *.apk | head -n 1) --app "1:977855311843:android:56f4c4446e9524009abad6
"
        env:
          GCP_SA_KEY: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
